name = "teak-email-master"
main = "worker.js"
compatibility_date = "2024-09-23"
account_id = "0f09e355edbde5f9b76e20ed10141729"
routes = [
  { pattern = "teak.email/*", zone_name = "teak.email" },
  { pattern = "www.teak.email/*", zone_name = "teak.email" }
]
